---
- name: Base configuration for all servers
  hosts: all
  become: yes

  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Upgrade packages
    apt:
      upgrade: dist

  - name: Install base utilities
    apt:
      name:
        - git
        - curl
        - unzip
        - htop
        - python3-pip
      state: present
